###############
### MONITOR ###
###############

monitor = , preferred, auto, 1




#################
### VARIABLES ###
#################

# Autostart

$wallpaper = ~/.wallpaper/wallpaper.png


# Environment Variables

$cursorsize = 24


# Keybinds

$mainMod = SUPER
$terminal = kitty
$menu = tofi-drun --drun-launch=true


# General

$inactiveCol = 0xff2f057d
$activeCol = 0xfff1f2e1
$kblayout = br


# Window Rules

$terminal = kitty
$terminalInactiveOpacity = 0.75


# DO NOT CHANGE

$confs = ~/.config/hypr/confs




###############
### SOURCES ###
###############

source = $confs/autostart.conf
source = $confs/envvars.conf
source = $confs/keybinds.conf
source = $confs/general.conf
source = $confs/windowrules.conf
