# Font

font_family monospace
font_size 11


# Background opacity

foreground #f1f2e1
background #010027
background_opacity 0.86666667


# Custom behaviour

confirm_os_window_close 0
scrollback_lines 0


# Remove window border

window_border_width 0


# Basic colours

foreground #f1f2e1
background #010027
selection_foreground #a06b1f
selection_background #edf37b


# Cursor

cursor #f1f2e1
cursor_text_color #00ff00
url_color #7b9af3
