from typing import List
from libqtile import bar, layout, widget
from libqtile.config import Click, Drag, Group, Key, Match, Screen
from libqtile.lazy import lazy
from libqtile.utils import guess_terminal
mod = "mod4"
terminal = "kitty"


# THE BIG 5

groups = [Group(i) for i in "123456789"]
for i in groups:
    keys.extend([
        Key([mod], i.name, lazy.group[i.name].toscreen(), desc = "Switch to group {}".format(i.name)),
        Key([mod, "shift"], i.name, lazy.window.togroup(i.name, switch_group = True), desc = "Switch to & move focused window to group {}".format(i.name)),
    ])

keys = [
    Key([mod], "w", lazy.window.kill(), desc = "Kill focused window"),
    Key([mod, "control"], "q", lazy.shutdown(), desc = "Shutdown Qtile"),
    Key([mod], "r", lazy.spawncmd(), desc = "Spawn a command using a prompt widget"),
    Key([mod], "n", lazy.next_layout(), desc = "Changes to the next layout"),
]

layouts = [
    layout.Max(),
    layout.Spiral(),
]

mouse = [
    Click([mod], "Button1", lazy.window.bring_to_front())
]

screens = [
    Screen(
        top = bar.Bar(
            [
                widget.GroupBox(disable_drag = True, highlight_method = "line"),
                widget.TaskList(),
                widget.Chord(
                    chords_colors={
                        'launch': ("#ff0000", "#ffffff"),
                    },
                    name_transform=lambda name: name.upper(),
                ),
                widget.TextBox("Press &lt;M-r&gt; to spawn", foreground="#d75f5f"),
                widget.Systray(),
                widget.Clock(),
            ],
            24,
        ),
    ),
]


# CONFIG VARS

auto_fullscreen = False
bring_front_click = "floating_only"
cursor_warp = False
dgroups_key_binder = None
dgroups_app_rules = []
extension_defaults = dict(font = 'sans', fontsize = 12, padding = 3)
floating_layout = 
focus_on_window_activation = "smart"
follow_mouse_focus = True
widget_defaults = dict(font = 'sans', fontsize = 12, padding = 3)
reconfigure_screens = True
wmname = "LG3D"
auto_minimize = True