###############
### MONITOR ###
###############

monitor = , preferred, auto, 1




#################
### VARIABLES ###
#################

# Autostart

$wallpaper = ~/.wallpaper/wallpaper.png


# Environment Variables

$cursorsize = 24


# Keybinds

$mainMod = SUPER
$terminal = kitty
$menu = rofi -show drun


# Input

$kblayout = br


# Aesthetics

######


# Window Rules

######


# DO NOT CHANGE

$confs = ~/.config/hypr/confs




###############
### SOURCES ###
###############

source = $confs/autostart.conf
source = $confs/envvars.conf
source = $confs/keybinds.conf
source = $confs/input.conf
source = $confs/aesthetics.conf
source = $confs/windowrules.conf
